trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'c0a6e7b6-1a69-4957-940d-2f1eb4478ad4'
  resourceGroup: 'rg-Myagent'
  containerAppName: 'ca-api-btwsshlh5cluo'
  acrName: 'testagent93'
  imageName: 'entra-agent-ui'
  containerName: 'entra-agent'  # Replace with your actual container name if different

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Azure login to access ACR
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(acrName)
  displayName: 'Login to Azure Container Registry'

# Step 2: Build and push Docker image (frontend build is inside Dockerfile)
- script: |
    docker build -f src/Dockerfile -t $(acrName).azurecr.io/$(imageName):$(Build.BuildId) .
    docker push $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

# Step 3: Deploy to Azure Container App
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az containerapp update \
        --name $(containerAppName) \
        --resource-group $(resourceGroup) \
        --image $(acrName).azurecr.io/$(imageName):$(Build.BuildId) \
        --container-name $(containerName)
  displayName: 'Deploy to Azure Container App'
